package com.ess.salaryadvance.common;

public enum FeatureAccess {
    DASHBOARD_VIEW,
    REQUEST_SUBMIT,
    REQUEST_HISTORY_VIEW,
    PENDING_APPROVAL_VIEW,
    APPROVE_REQUEST,
    USER_MANAGEMENT,
    APPROVED_ADVANCES_VIEW,
    ADVANCE_PROCESS,
    SYSTEM_HEALTH_VIEW,
    AUDIT_LOG_VIEW,
    REPORTS_VIEW,
    SETTINGS_MANAGE,
    NOTIFICATIONS_VIEW
}
